---
name: Bug Report
description: Create a report to help us improve
title: '[BUG] '
labels: [bug]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: dropdown
    id: severity-level
    attributes:
      label: Severity Level
      description: Select the severity level of this bug
      options:
        - Critical (S1) - Prevents app usage or causes data loss
        - High (S2) - Major functionality broken or unusable
        - Medium (S3) - Feature partially working, workaround exists
        - Low (S4) - Minor issues, cosmetic problems
    validations:
      required: true
  - type: dropdown
    id: priority-level
    attributes:
      label: Priority Level
      description: Select the priority level for fixing this bug
      options:
        - P1 - Must fix immediately
        - P2 - Fix as soon as possible
        - P3 - Fix when time permits
        - P4 - Fix if time allows
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide details about your environment
      placeholder: |
        - Device: [e.g. iPhone 12, Samsung Galaxy S21]
        - OS: [e.g. iOS 15.4, Android 12]
        - Browser: [e.g. Safari, Chrome]
        - Version: [e.g. 22]
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here. 