---
name: Feature Request
description: Suggest an idea for this project
title: '[FEATURE] '
labels: [enhancement]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!
  - type: textarea
    id: problem-description
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: Please write your user story in the following format
      placeholder: |
        As a [type of user],
        I want [goal]
        So that [benefit]
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: List the acceptance criteria for this feature
      placeholder: |
        - Criteria 1
        - Criteria 2
        - Criteria 3
    validations:
      required: true
  - type: dropdown
    id: priority-level
    attributes:
      label: Priority Level
      description: Select the priority level for implementing this feature
      options:
        - P1 - Must implement immediately
        - P2 - Implement as soon as possible
        - P3 - Implement when time permits
        - P4 - Implement if time allows
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here. 