---
name: Feature Request
about: Suggest an idea for this project
title: '[FEATURE] '
labels: enhancement
assignees: ''
---

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**User Story**
As a [type of user],
I want [goal]
So that [benefit]

**Acceptance Criteria**
- [ ] Criteria 1
- [ ] Criteria 2
- [ ] Criteria 3

**Additional context**
Add any other context or screenshots about the feature request here.

**Priority Level**
- [ ] P1 - Must implement immediately
- [ ] P2 - Implement as soon as possible
- [ ] P3 - Implement when time permits
- [ ] P4 - Implement if time allows 