name: Spell and Grammar Check

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

# Add permissions block at the workflow level
permissions:
  issues: write
  contents: read

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install -g textlint
          npm install -g textlint-rule-spellcheck-tech-word
          npm install -g textlint-rule-common-misspellings
          npm install -g textlint-rule-no-dead-link

      - name: Create textlint configuration
        run: |
          echo '{
            "rules": {
              "spellcheck-tech-word": true,
              "common-misspellings": true,
              "no-dead-link": true,
            }
          }' > .textlintrc

      - name: Run spell and grammar check and capture errors
        id: check
        run: |
          # Initialize errors array
          echo "[]" > errors.json
          
          # Find only markdown files and check them
          find . -type f -name "*.md" -not -path "*/node_modules/*" -not -path "*/\.*" | while read file; do
            echo "Checking $file..."
            # Run textlint and capture the output
            textlint --format json "$file" > lint_output.json || true
            
            # Debug: Print the content of lint_output.json
            echo "Content of lint_output.json:"
            cat lint_output.json
            
            # Process the output and add to errors.json if there are issues
            if [ -s lint_output.json ]; then
              # Extract file path, line numbers, and messages
              jq -r 'if type == "array" then .[] else . end | {file: .filePath, line: .line, message: .message}' lint_output.json >> errors.json
            fi
          done
          
          # Debug: Print the content of errors.json
          echo "Content of errors.json:"
          cat errors.json
          
          # Check if errors.json contains any errors
          if [ -s errors.json ] && [ "$(jq 'length' errors.json)" -gt 0 ]; then
            echo "Errors found in markdown files"
            exit 1
          fi

      - name: Create Issue for Spelling and Grammar Issues
        if: failure()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const branch = context.ref.replace('refs/heads/', '');
            
            // Read the errors.json file
            const fs = require('fs');
            let errors = [];
            try {
              const fileContent = fs.readFileSync('errors.json', 'utf8');
              errors = JSON.parse(fileContent);
            } catch (error) {
              console.error('Error reading errors.json:', error);
            }
            
            // Group errors by file
            const errorsByFile = {};
            errors.forEach(error => {
              if (!errorsByFile[error.file]) {
                errorsByFile[error.file] = [];
              }
              errorsByFile[error.file].push({
                line: error.line,
                message: error.message
              });
            });
            
            // Create the issue body
            let issueBody = `Spelling and writing style issues were found in markdown files in the ${branch} branch.\n\n`;
            
            // Add details for each file
            for (const [file, fileErrors] of Object.entries(errorsByFile)) {
              issueBody += `### ${file}\n`;
              fileErrors.forEach(error => {
                issueBody += `- Line ${error.line}: ${error.message}\n`;
              });
              issueBody += '\n';
            }
            
            // If no specific errors were found, add a generic message
            if (Object.keys(errorsByFile).length === 0) {
              issueBody += "No specific errors were captured. Please check the GitHub Actions logs for details.\n";
            }
            
            issueBody += `\nPlease fix these issues to maintain document quality.`;
            
            try {
              await github.rest.issues.create({
                owner,
                repo,
                title: `Spelling and Writing Style Issues Found in ${branch}`,
                body: issueBody,
                labels: ['spelling', 'writing-style', 'documentation']
              });
            } catch (error) {
              console.error('Error creating issue:', error);
              // Log the error details for debugging
              console.error('Error details:', JSON.stringify(error, null, 2));
            }